apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullName }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.internalPort }}
      targetPort: {{ .Values.service.internalPort }}
      nodePort: {{ .Values.service.externalPort }}
      protocol: TCP
      name: {{ .Values.fullName }}
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
